### ISSUE TITLE
Data set for the help file example code

### ISSUE THREAD

**Issue by ericmelse** [eckerale/agrm#1]
Dear Alejandro,

Thank you for writing the Stata module `agrm` to calculate van der Eijk's measure of agreement.

To exercise the help file example, which data set are you using?
If not available somewhere, can you provide it here to download it?

Thank you,
Eric

**Comment by eckerale** [comment]
Dear David,
Thank you for the comment and the suggestion. I have updated the examples section with an application example of perceptual agreement on the ideological placement of political parties among voters (very similar to the application in the original van der Eijk paper). The corresponding data snippet has also been uploaded. I hope this makes the example a bit more accessible since I was also unable to recover/recall which data file I originally used. Hope this helps.
Best,
Alejandro
